### GET /
GET http://localhost:8080 HTTP/1.1

### POST /auth/register
POST http://localhost:8080/auth/register HTTP/1.1
Content-Type: application/json

{
  	"email": "john@gmail.com",
  	"password": "John123!",
  	"confirm_password": "John123!"
}

### POST /auth/login
POST http://localhost:8080/auth/login HTTP/1.1
Content-Type: application/json

{
  	"email": "johnny@gmail.com",
  	"password": "John123!"
}



### GET /auth
GET http://localhost:8080/auth HTTP/1.1

### POST /auth/signout
POST http://localhost:8080/auth/signout HTTP/1.1

### GET /users
GET http://localhost:8080/users HTTP/1.1


### GET /orders
GET http://localhost:8080/orders HTTP/1.1

### GET /orders/chart
GET http://localhost:8080/orders/chart HTTP/1.1

### PATCH /users/:id
PATCH http://localhost:8080/users/c706daf9-c2bb-4242-8062-9544d0cf522a HTTP/1.1
Content-Type: application/json

{
	"role_id": "cec4e05a-a93e-4ce9-903e-4d880f071b28"
}

### GET /permissions
GET http://localhost:8080/permissions HTTP/1.1


### POST /permissions
POST http://localhost:8080/permissions HTTP/1.1
Content-Type: application/json

{
	"name": "edit_permissions"
}

### GET /roles
GET http://localhost:8080/roles HTTP/1.1

### POST /roles
POST http://localhost:8080/roles HTTP/1.1
Content-Type: application/json

{
	"name": "Viewer",
	"permissions": [
		"cae93961-e3dc-4111-b870-01f52e0de0dd"
	]
}

### PATCH /roles/:id
PATCH http://localhost:8080/roles/f81a390b-0597-4509-8743-b47dc870fea1 HTTP/1.1
Content-Type: application/json

{
	"name": "Admin",
	"permissions": [
		"65205de4-203d-4d0e-a392-bedd6449f58c",
		"f91af581-7311-44fa-a5a5-455820d692a1"
	]
}

### DELETE /roles/{id}
DELETE http://localhost:8080/roles/21c77c09-c191-4d60-8104-66656afa0994 HTTP/1.1

